---
title: "將power BI的工作表匯出為csv檔"
date: "2025-03-02"
tags:
- power BI
categories:
- 資料整理
---

Power BI是微軟提供的一款免費的視覺化工具，也支援資料清理和轉換。但畢竟使用的是DAX語法，不一定是自身慣用的語法。若拿到的是Power BI資料，想要匯出數據，用自己熟悉的工具來處理資料，該如何做呢？

<!--more-->

Power BI是微軟提供的一款免費的視覺化工具，可做視覺化的圖表後，將結果匯出。但，若是想匯出資料表，以其他工具來做處理，可以怎麼做呢？本文簡介如何在power BI中匯出csv檔。

## 所需軟體

除了power BI之外，尚需先安裝DAX Studio。


## 匯出資料

1. 開啟power BI，打開欲匯出的資料庫。

2. 開啟DAX Studio。在開啟DAX Studio時，會出現Connect視窗。

3. 在Connect視窗中，「Power BI/SSDT Model」的選項中應會自動出現Power BI已開啟的資料庫名稱。

4. 點選「Power BI/SSDT Model」後，按「Conncet」，即可看到資料庫的工作表。

5. 點選「Advanced」 &rarr; 「Export Data」 &rarr; 「CSV files」 。

6. 在Export Data視窗中，設定好要儲存的資料夾(Output Path)、CSV Delimiter(視情況選擇，一般是Comma)和File Encoding(視資料而定)，按「Next」。

7. 選取欲匯出的資料表(預設為全選)，按「Export」。

8. 匯出完成後按「Close」即可。


若是資料量較小，想匯出的資料表也不多，則不需要用到DAX Studio。直接點選Power BI左側欄位的「資料表檢視」，進入資料表檢視視窗。在右側的「資料」功能表中，對想匯出的資料表按右鍵，選擇「複雜資料表」，再將複製的資料貼到Excel即可。

## 參考資料

1. [Using DAX Studio to Export Over 1 Million Rows of Data From Power BI](https://urbizedge.com/using-dax-studio-to-export-over-1-million-rows-of-data-from-power-bi/)

