---
title: "以部份文字重新命名google表單的欄位名稱"
date: "2022-10-05"
tags:
- google表單
- String
- R
categories:
- 資料整理
---

Google表單所生成的excel檔，欄位名稱可能會很長。我們可以抽取部份的文字來重新命名欄位名稱。

<!--more-->

Google表單所生成的excel檔，欄位名稱可能會很長。我們可以抽取部份的文字來重新命名欄位名稱。


## 範例資料

假設google表單的部份資料欄位名稱長得像這樣：

「1-7 你如何得知本系? (可複選)_朋友、同學、學長姐」  
「1-7 你如何得知本系? (可複選)_報考簡章」  
「1-7 你如何得知本系? (可複選)_學校聲望」  
「1-8  你選擇本系時，下列原因有多重要？ [(1) 最符合興趣]」  
「1-8  你選擇本系時，下列原因有多重要？ [(2) 喜歡課程]」  
「1-8  你選擇本系時，下列原因有多重要？ [(3) 畢業後出路不錯]」  


我們希望將欄位名稱中重覆的部份拿掉，改為：

「朋友、同學、學長姐」  
「報考簡章」  
「學校聲望」  
「(1) 最符合興趣」  
「(2) 喜歡課程」  
「(3) 畢業後出路不錯」  

此時可以藉由sub()、strsplit()等函數，依據某些規則來抽取部份文字，取代原本的欄位名稱。例如1-7的題目可抽取)_後的文字、1-8的題目抽取括號裡的文字，以取代原本的欄位名稱。

## 以strsplit()函數抽取部份文字

令變項str1為「1-7 你如何得知本系? (可複選)_朋友、同學、學長姐」，我們可以藉由strsplit()函數將這個字串改成「朋友、同學、學長姐」。作法如下：

```{R}
str1 <- "1-7 你如何得知本系? (可複選)_朋友、同學、學長姐"
```
首先用strsplit()函數將字串str1分割，分割的依據是")_"。

```{R}
strsplit(str1, "[)_]")
```
由程式執行的結果可以看到，strsplit()函數已經將原來的字串str1分割為三個部份：

[[1]]  
[1] "1-7 你如何得知本系? (可複選"  
[2] ""  
[3] "朋友、同學、學長姐"  

要將str1改為「朋友、同學、學長姐」，則只要用[[1]][3]把這部份抽取出來即可。

```{R}
str1 <- strsplit(str1, "[)_]")[[1]][3]
```

### 一次改變多個欄位名稱

假設上述三個題目在某個資料框df1的第2到第4個欄位，則只要將上面的程式碼寫入for迴圈中即可一次改變多個欄位的名稱。

```{R eval=FALSE}
for (i in c(2:4)){
  names(df1)[i] <- strsplit(names(df1[i]), "[)_]")[[1]][3]
}
```

## 以sub()函數抽取部份文字

令變項str1為「1-8  你選擇本系時，下列原因有多重要？ [(1) 最符合興趣]」。

```{R}
str1 <- "1-8  你選擇本系時，下列原因有多重要？ [(1) 最符合興趣]"
```

我們可以藉由sub()函數，抽取中括號內的文字，將字串str1改成「(1) 最符合興趣」，作法如下。

在下列程式碼中，```".*\\[([^*]+)].*"```為regular expression，其中```.*```指的是任何文字，```\\[```為文字[，```([^*]+)```指的是一個group，此group中是任何字元(```[^.*]+```)都可以，接著是文字```]```和任何文字```.*```。第二個參數```\\1```表示抽取出的第一個group。

```{R}
sub(".*\\[([^.*]+)].*", "\\1", str1)
```

若要將str1改為「朋友、同學、學長姐」，只要將原字串以抽取出的文字(\1)取代即可。

```{R}
str1 <- sub(".*\\[([^.*]+)].*", "\\1", str1)
str1
```

### 一次改變多個欄位名稱

假設上述三個題目在某個資料框df1的第5到第7個欄位，則只要將上面的程式碼寫入for迴圈中即可。

```{R eval=FALSE}
for (i in c(5:7)){
  names(df1)[i] <- sub(".*\\[([^.*]+)].*", "\\1", names(df1)[i])
}
```

## 參考資料
1. Wiktor Stribiżew's reply to [Extract last substring between square brackets](https://stackoverflow.com/questions/44127419/extract-last-substring-between-square-brackets) @stack overflow
2. [Regular expressions](https://cran.r-project.org/web/packages/stringr/vignettes/regular-expressions.html)
3. [R for Data Science](https://r4ds.had.co.nz/strings.html)