---
title: "以tidyr和dplyr套件整理Google表單的複選題資料"
date: "2022-09-29"
tags:
- google表單
- 複選題
- R
- tidyr
- dplyr
categories:
- 資料整理
  
---

Google表單在題目為複選題時，會將填答者的回應全記錄在同一個欄位，不利後續分析。本文說明如何用R的tidyr和dplyr套件的函數來處理Google表單的複選題資料，以利做後續分析。更簡單的作法是用splitstackshape套件來做，請見[此文](multiple-choice-splitstackshape)。

<!--more-->

Google表單在題目為複選題時，會將填答者的回應全記錄在同一個欄位，不利後續分析。本文說明如何用R的tidyr和dplyr套件的函數來處理Google表單的複選題資料，以利做後續分析。更簡單的作法是用splitstackshape套件來做，請見[此文](https://ccwupsy.github.io/2022/10/以splitstackshape套件整理google表單的複選題資料/)。

## 資料範例

請[點選此處](https://docs.google.com/spreadsheets/d/1Z9hGVdNaNmk41hbScOB1SUzTVZ_An41Z/edit?usp=sharing&ouid=102534642616283273245&rtpof=true&sd=true)下載google forms的資料範例。

資料為一虛擬的問卷資料，為25位大學生在五個問卷題目的回答。其中兩個題目是複選題，另有三個題目是四點量表的回答。

## 讀入資料

```{R}
library(data.table)
library(readxl)
qData1 <- as.data.table(read_xlsx('GoogleFormsData.xlsx'))
```

```{R, echo=FALSE}
library(knitr)
library(kableExtra)
kbl(head(qData1[, c(1:6)]), align = "c") %>%
  kable_styling(bootstrap_options = "striped", font_size = 12.5)
```


## 重新整理複選題資料-以單一題目為例

用tidyr套件的seperate()函數將第2個column--"你在高中時期擔任過哪些職務？"中的回答按照逗號(,)分割，並置於不同行。這些新的行以"你在高中時期擔任過哪些職務？-1"到"你在高中時期擔任過哪些職務？-5"來命名。

```{R warning=FALSE}
library(tidyr)
qData1 <- separate(qData1, 2, paste0("你在高中時期擔任過哪些職務？-", 1:5), sep=',', remove=F)
```

```{R, echo=FALSE}
library(knitr)
library(kableExtra)
kbl(head(qData1[, c(2:7)]), align = "c") %>%
  kable_styling(bootstrap_options = "striped", font_size = 12.5)
```

用tidyr套件的gather()函數，將Wide-format data轉為long-format data。原本有五行(即第3~7行)，每行的值都是所擔任的幹部名稱。gather()可以將這五行合併為一行(key)，並將每一行下面的反應放到新的一行(value)中。我們可以設定key column的名稱和value column的名稱。

```{R}
qData1 <- gather(qData1, key = "你在高中時期擔任過哪些職務？-new", value = value, c(3:7)) 
```  

用na.exclude()函數移除value一行中，數值為NA的列。讓資料更為精簡。
```{R}
qData1 <- na.exclude(qData1, ncol(qData1)) 
```

用dplyr套件的mutate()函數將value改為題目敘述加上原有的職務名稱，並將"你在高中時期擔任過哪些職務？-new"都設為1。
```{R message=FALSE}
library(dplyr)
qData1 <- mutate(qData1, value=paste0("你在高中時期擔任過哪些職務？", '-', value), "你在高中時期擔任過哪些職務？-new"=1)
```

用tidyr套件的spread()函數將value column中的值設為key，"你在高中時期擔任過哪些職務？-new"的值設為value，將long-format data轉為wide-format data。

```{R}
qData1 <- spread(qData1, key = value, value = "你在高中時期擔任過哪些職務？-new") 
```

用dplyr套件的mutate_all()函數，將第7~16個columns的na都取代為0。

```{R}
qData1 <- mutate_at(qData1, vars(c(7:16)), ~replace(., is.na(.), 0))
```

```{R, echo=FALSE}
library(knitr)
library(kableExtra)
kbl(qData1[1:6, c(2, 7:10)], align = "c") %>%
  kable_styling(bootstrap_options = "striped", font_size = 12.5)
```

## 將上述程式改為變數

新設一變數thiscname，令之為"你在高中時期擔任過哪些職務？"，並將上面程式碼中的column位置的數字全數以變數來表示。在gather函數中，key必須是string或symbols，在此我們直接設為"key"即可。

```{R warning=FALSE}
qData1 <- as.data.table(read_xlsx('GoogleFormsData.xlsx'))
ncolumn <- 2
thiscname <- names(qData1)[ncolumn]
qData1 <- separate(qData1, ncolumn, paste0(thiscname, "-", 1:5), sep=',', remove=F)
qData1 <- gather(qData1, key = key, value = value, c(all_of(ncolumn+1):all_of(ncolumn+5))) 
qData1 <- na.exclude(qData1, ncol(qData1)) 
qData1 <- mutate(qData1, value=paste0(thiscname, '-', value), key=1)
cn1 <- ncol(qData1)-1
qData1 <- spread(qData1, key = value, value = key) 
cn2 <- ncol(qData1)
qData1 <- mutate_at(qData1, vars(c(all_of(cn1):all_of(cn2))), ~replace(., is.na(.), 0))
```


## 以for迴圈一次處理所有複選題的題目

加上for迴圈後，即可一次處理多個複選題的回答。

```{R warning=FALSE}
qData1 <- as.data.table(read_xlsx('GoogleFormsData.xlsx'))

col_pos <- c(2,6)
cname <- names(qData1)[col_pos]

for (i in 1:length(cname)) {
  thiscname <- cname[i]
  thisncolumn <- col_pos[i]
  qData1 <- separate(qData1, thisncolumn, paste0(thiscname, "-", 1:5), sep=',', remove=F)
  qData1 <- gather(qData1, key = key, value = value, c(all_of(thisncolumn+1):all_of(thisncolumn+5))) 
  qData1 <- na.exclude(qData1, ncol(qData1)) 
  qData1 <- mutate(qData1, value=paste0(thiscname, '-', value), key=1)
  cn1 <- ncol(qData1)-1
  qData1 <- spread(qData1, key = value, value = key) 
  cn2 <- ncol(qData1)
  qData1 <- mutate_at(qData1, vars(c(all_of(cn1):all_of(cn2))), ~replace(., is.na(.), 0))
}

```



## 寫成函數

最後將上述程式碼寫成函數，只要輸入dataframe的名稱和複選題在第幾行，就可以帶入函數處理。在下例中，函數名稱為arr_mulchoice，輸入的變數為df（dataframe的名稱）和col_pos（哪些題目是複選題需要處理）。

```{R warning=FALSE}

arr_mulchoice <- function(df, col_pos){
  cname <- names(qData1)[col_pos]
  for (i in 1:length(cname)) {
    thiscname <- cname[i]
    thisncolumn <- col_pos[i]
    df <- separate(df, thisncolumn, paste0(thiscname, "-", 1:5), sep=',', remove=F)
    df <- gather(df, key = key, value = value, c(all_of(thisncolumn+1):all_of(thisncolumn+5))) 
    df <- na.exclude(df, ncol(df)) 
    df <- mutate(df, value=paste0(thiscname, '-', value), key=1)
    cn1 <- ncol(df)-1
    df <- spread(df, key = value, value = key) 
    cn2 <- ncol(df)
    df <- mutate_at(df, vars(c(all_of(cn1):all_of(cn2))), ~replace(., is.na(.), 0))
  }
return(df)
}

qData1 <- as.data.table(read_xlsx('GoogleFormsData.xlsx'))
col_pos <- c(2,6)
qData1 <- arr_mulchoice(qData1, col_pos)

```

## 參考資料
Adam Quek's answer @Stack overflow: [R: How to separate multiple choice, multiple answers questionnaire data that Google Forms put in one variable?](https://stackoverflow.com/questions/44109108/r-how-to-separate-multiple-choice-multiple-answers-questionnaire-data-that-goo)

